tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ack'
brew 'awscli'
brew 'base64'

brew 'checkbashisms'
brew 'dos2unix'
brew 'git'
brew 'hub'
brew 'icu4c'
brew 'jq'
brew 'lastpass-cli', args: ['with-pinentry']
brew 'openssl'
brew 'polipo'
brew 'p7zip'
brew 's3cmd'
brew 'sleepwatcher'
brew 'tmux'
brew 'zsh'

cask 'alfred'
cask 'apache-directory-studio'
cask 'appcleaner'
cask 'atom'
cask 'calibre'
cask 'crashplan'
cask 'dropbox'
cask 'evernote'
cask 'fantastical'
cask 'firefox'
cask 'fitbit-connect'
cask 'flux'
cask 'garmin-express'
cask 'github-desktop'
cask 'google-chrome'
cask 'google-drive'
cask 'item2'
cask 'magicprefs'
cask 'moneydance'
# cask 'onenote' # Doesn't exist
# cask 'pixelmator' # Doesn't exist
cask 'skype'
cask 'skitch'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'telegram'
cask 'textexpander'
cask 'today-scripts'
cask 'torbrowser'
cask 'transmission'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'viscosity'
cask 'vmware-fusion'
cask 'wireshark'
# cask 'wunderlist' # Doesn't exist
