cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'caskroom/fonts'
tap 'caskroom/versions' # Needed for beta versions
tap 'caskroom/drivers'  # Needed for garmin-express
tap 'shopify/shopify'   # Needed for toxiproxy
cask 'java'             # Needs to be first so dependents can be installed.

brew 'ansible'
brew 'autossh'
brew 'awscli'
brew 'base64'
brew 'bat'              # Like cat, but prettier
brew 'checkbashisms'
brew 'coreutils'
brew 'diff-so-fancy'
brew 'dos2unix'
brew 'exa'
brew 'exercism'
brew 'findutils'
brew 'fswatch'
brew 'fzf'
brew 'git'
brew 'git-lfs'
brew 'gnu-sed'
brew 'go'
brew 'heroku'
brew 'htop'
brew 'httpie'
brew 'hub'
brew 'icu4c'
brew 'jq'
brew 'lockrun'
brew 'mackup'
brew 'moreutils'
brew 'openssl'
brew 'pinentry-mac'
brew 'p7zip'
brew 'prettyping'
brew 'pstree'
brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'restic'
brew 'ripgrep'  # rg, an even faster version of ag
brew 'rsync'
brew 's3cmd'
brew 'shellcheck'
brew 'the_silver_searcher' # ag, a faster ack
brew 'tldr'
brew 'tmux'
brew 'toxiproxy'  # Requires "tap 'shopify/shopify'" above.
brew 'xz'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'aerial'
cask 'alfred'
cask 'amazon-drive'
cask 'amazon-music'
cask 'apache-directory-studio'
cask 'appcleaner'
cask 'arq'
cask 'atom-beta'
cask 'banktivity'
cask 'bartender'
cask 'calibre'
cask 'dash'
cask 'divvy'
cask 'docker'
cask 'dropbox'
cask 'encryptme'
cask 'etcher'
cask 'exodus'
cask 'fantastical'
cask 'firefox-beta'
cask 'flux'
cask 'garmin-express'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-backup-and-sync'
cask 'gpg-suite'
cask 'imagealpha'
cask 'imageoptim'
cask 'iterm2'
cask 'licecap'
#cask 'little-snitch'
cask 'keybase'
cask 'muzzle'
cask 'netspot'
cask 'numi'
cask 'pallotron-yubiswitch'
cask 'postman'
cask 'qbserve'
cask 'rocket'
#cask 'skype'
cask 'skitch'
cask 'sketch'
cask 'slack'
cask 'sloth'
cask 'spotify'
cask 'teamviewer'
cask 'textexpander5'
#cask 'the-unarchiver' - download temporarily broken
cask 'torbrowser'
cask 'transmission'
cask 'vagrant'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'viscosity'
#cask 'vlc'
cask 'vmware-fusion'
cask 'whatsapp'
cask 'wireshark'

# AppStore Apps that need manual install for the mo.
# bear
# magnet
# managed software center - github
# microsoft onenote
# microsoft remote desktop
# monosnap
# opendns roaming client - github
# pixelmator

# Ano apps
# logitech camera settings
