cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'caskroom/fonts'
cask 'java'   # Needs to be first so dependents can be installed.

brew 'ack'
brew 'awscli'
brew 'base64'
brew 'bfg'
brew 'checkbashisms'
brew 'dos2unix'
brew 'git'
brew 'gnu-sed'
brew 'go'
brew 'hub'
brew 'icu4c'
brew 'jq'
brew 'lastpass-cli', args: ['with-pinentry']
brew 'openssl'
brew 'polipo'
brew 'p7zip'
brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'rbenv-readline'
brew 'homebrew/dupes/rsync'
brew 's3cmd'
brew 'sleepwatcher'
brew 'speedtest-cli'
brew 'tmux'
brew 'xz'
brew 'zsh'

cask '1password'
cask 'alfred'
cask 'apache-directory-studio'
cask 'appcleaner'
cask 'atom'
cask 'calibre'
cask 'crashplan'
cask 'dropbox'
cask 'duet'
cask 'evernote'
cask 'fantastical'
cask 'firefox'
cask 'fitbit-connect'
cask 'flux'
cask 'garmin-express'
cask 'github-desktop'
cask 'google-chrome'
cask 'google-drive'
cask 'imagealpha'
cask 'imageoptim'
cask 'iterm2'
cask 'magicprefs'
cask 'moneydance'
cask 'skype'
cask 'skitch'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'telegram'
cask 'textexpander'
cask 'today-scripts'
cask 'torbrowser'
cask 'transmission'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'viscosity'
cask 'vmware-fusion'
cask 'wireshark'

# AppStore Apps that need manual install for the mo.
# cask 'onenote' # Doesn't exist
# cask 'pixelmator' # Doesn't exist
# cask 'wunderlist' # Doesn't exist
