cask_args appdir: '/Applications'
# tap 'shopify/shopify'          # Needed for toxiproxy
tap 'github/gh'                 # Needed for gh
tap 'heroku/brew'               # Needed for heroku
tap 'homebrew/bundle'
tap 'homebrew/cask-drivers'     # Needed for garmin-express
tap 'homebrew/cask-fonts'       # Needed for fonts
tap 'homebrew/cask-versions'    # Needed for beta versions
tap 'homebrew/cask'
tap 'jesseduffield/lazydocker'  # Needed for lazydocker
tap 'jgavris/rs-git-fsmonitor'
tap 'muesli/homebrew-tap/duf'
tap 'yqrashawn/goku'            # Needed for goku

brew 'act'              # Run GitHub Actions locally
brew 'ansible'
brew 'awscli'
brew 'azure-cli'
brew 'base64'
brew 'bash'             # Only needed for my Bash scripts now macOS isn't shipping updates etc
brew 'bat'              # Like cat, but prettier
brew 'checkbashisms'
brew 'coreutils'
brew 'diff-so-fancy'
brew 'dos2unix'
brew 'duf'
brew 'exa'
brew 'exercism'
brew 'fd'               # Like find, but faster
brew 'findutils'
brew 'fish'
brew 'fswatch'
brew 'fzf'
brew 'fzy'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'git-lfs'
brew 'gnu-sed'
brew 'gnupg'
brew 'go'
brew 'goku'
brew 'grc'              # General colorizer
brew 'heroku'
brew 'htop'
brew 'httpie'
brew 'hub'
brew 'hugo'
brew 'icdiff'
brew 'icu4c'
brew 'jq'
brew 'lazydocker'
brew 'lazygit'
brew 'lcov'
brew 'lesspipe'
brew 'lockrun'
brew 'mas' # CLI tool for installing Mac App Store apps at the end of this file.
brew 'moreutils'
brew 'mosh'
brew 'neovim'
brew 'openssl'
brew 'pinentry-mac'
brew 'p7zip'
brew 'prettyping'
brew 'pstree'
brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-default-gems'
brew 'rclone'
brew 'restic'
brew 'ripgrep' # rg, an even faster version of ag
brew 'rs-git-fsmonitor' # Run `git config core.fsmonitor rs-git-fsmonitor` in large repos you want this magic in
brew 'rsync'
# brew 'rubyfmt' # Often outdated. Use precompile bin from https://github.com/penelopezone/rubyfmt/releases instead
brew 's3cmd'
brew 'shellcheck'
brew 'tldr'
brew 'tmux'
# brew 'toxiproxy'  # Requires "tap 'shopify/shopify'" above.
brew 'watch'
brew 'xz'
# brew 'zsh'
# brew 'zsh-completions'

cask '1password'
cask '1password-cli'
cask 'aerial' # Aerial screensaver
cask 'alfred'
# cask 'amazon-drive'
# cask 'amazon-music'
# cask 'apache-directory-studio'
cask 'android-file-transfer' # Used as a backup to transfer files from my Garmin
cask 'appcleaner'
# cask 'arq'
# cask 'atom-beta'
# cask 'banktivity'
cask 'bartender'
cask 'calibre'
cask 'chatmate-for-whatsapp'
cask 'dash'
cask 'divvy'
cask 'docker'
cask 'dropbox'
cask 'encryptme'
cask 'etcher'
cask 'exodus'
cask 'fantastical'
cask 'firefox'
cask 'fliqlo'
cask 'flux'
cask 'font-jetbrains-mono'
cask 'garmin-express'
cask 'google-chrome'
cask 'google-cloud-sdk'
# cask 'google-backup-and-sync'
# cask 'gpg-suite-no-mail'
cask 'gpg-suite-pinentry'
cask 'hammerspoon'
cask 'hey'
cask 'imagealpha'
cask 'imageoptim'
# cask 'insomnia' # Alternative to Postman
cask 'iterm2'
cask 'font-jetbrainsmono-nerd-font'
cask 'little-snitch'
cask 'kap'
cask 'karabiner-elements'
cask 'keybase'
cask 'microblog'
cafsk 'microsoft-edge'
# cask 'microsoft-teams'
cask 'muzzle'
cask 'netnewswire'
cask 'netspot'
cask 'numi'
# cask 'pallotron-yubiswitch'
cask 'postman'
cask 'qbserve'
cask 'qlmarkdown'   # QuickLook support for markdown
cask 'qlimagesize'  # QuickLook support for webp and showing image dimensions
# cask 'rocket'
# cask 'skype'
cask 'skitch'
cask 'sketch'
cask 'slack'
cask 'spotify'
# cask 'teamviewer'
cask 'telegram'
cask 'textexpander'
cask 'the-unarchiver'
cask 'transmission'
cask 'transmit'
# cask 'vagrant'
# cask 'virtualbox'
# cask 'virtualbox-extension-pack'
cask 'viscosity'
cask 'visual-studio-code'
# cask 'vlc'
# cask 'vmware-fusion'
# cask 'wireshark' # This is having problems installing at the mo - Oct 2019.
# cask 'yubico-yubikey-manager'
# cask 'zwift'

# AppStore Apps that need manual install for the mo.
mas 'Bear', id: 1_091_189_122
mas 'Magnet', id: 441_258_766
mas 'Microsoft OneNote', id: 784_801_555
mas 'Microsoft Remote Desktop 10', id: 1_295_203_466
mas 'Monit', id: 1_014_850_245
mas 'Monosnap', id: 540_348_655
mas 'Pixelmator', id: 407_963_104
mas 'pomodorome', id: 1_484_801_884
mas 'Tot', id: 1_491_071_483
mas 'WireGuard', id: 1_451_685_025

