#!/usr/bin/env bash
#
# Return the password for an SSH key from 1Password - this is used by `install-1password-secrets` to load the SSH keys.
#
# This expects all the password entries in the Dotfiles vault to contain the private key filename in the title.
#
set -euo pipefail
[ -z "${1:-}" ] && ( echo "SSH private key filename required!"; exit 1 )
path=$(echo "$1" | sed 's|.*\(/.*\):|\1|')
filename=$(basename $path)
item_id=$(op list items --vault Dotfiles | jq -r '.[] | select(.templateUuid=="005") | select(.overview.title | endswith("'$filename'")) | .uuid')

# Returns the password in plaintext
if [ -n "$item_id" ]; then
  op get item $item_id | jq -r '.details.password'
fi