#!/usr/bin/env bash
#
# bootstrap installs things.
set -euo pipefail

DOTFILES=$(cd "$(dirname "$0")/.." && pwd)
# shellcheck source=bin/lib.sh
source "$DOTFILES/bin/lib.sh"

#### Default config opts ####
export DEFAULT_SHELL=${DEFAULT_SHELL:-fish}
touch "$HOME/.secrets"

create_my_std_dirs() {
  cd "$HOME" || exit 1

  mkdir -p "$HOME/Downloads"
  link_file Downloads tmp

  local dirs="bin tmp/trash Development"

  for dir in $dirs; do
    if [ ! -d "$HOME/$dir" ]; then
      msg="Created $HOME/$dir"
      if mkdir "$HOME/$dir"; then success "$msg"; else fail "$msg"; fi
    else
      success "Skipped $HOME/$dir already exists"
    fi
  done
}

### Lets go ###

info "Bootstrapping to $HOME..." "👢"
echo

install_dotfiles
create_my_std_dirs
echo
info "Installing and updating dependencies..."

# shellcheck source=bin/dot
if "$DOTFILES/bin/dot" 2>&1 | indent; then
  success "Dependencies installed"
else
  fail "Error installing or updating dependencies"
fi

echo ''
info 'All installed! 🏁' "🏁"
