#!/usr/bin/env bash
#
set -euo pipefail
DIR=$(cd "$(dirname "$0")/.." && pwd)

#### Default config opts ####
[ "$(uname -s)" = "Darwin" ] && MACOS=1 && OS=macos
[ "$(uname -s)" = "Linux" ] && LINUX=1 && OS=linux

export MACOS=${MACOS:-}
export LINUX=${LINUX:-}
export GITHUB_WORKSPACE=${GITHUB_WORKSPACE:-}
export DEFAULT_SHELL=${DEFAULT_SHELL:-fish}
BREWFILE="$DIR/$OS/Brewfile"

#### Lets GO!! ####
echo "👢 Bootstrapping to $HOME…"

echo "🏡 Arranging the furniture…"
cd "$HOME" || exit 1

for dir in bin Downloads Development; do
  mkdir -p "$HOME/$dir"
done
ln -Ff -s Downloads tmp
mkdir -p "$HOME/tmp/trash"
[ -f "$BREWFILE" ] && ln -Ff -s "$BREWFILE" .Brewfile

# Only install Homebrew if we've got a $HOME/.Brewfile
if ! command -v brew &> /dev/null && [ -f "$HOME/.Brewfile" ]; then
  echo '🍺 Installing Homebrew…'
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" > "$HOME/tmp/homebrew.log" 2>&1

  if [ $LINUX ]; then
    if [ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
      # If I have sudo access on the host, Homebrew will be here
      eval $(SHELL=bash /home/linuxbrew/.linuxbrew/bin/brew shellenv)
    else
      # Else it'll be in my homedir
      eval $(SHELL=bash $HOME/.linuxbrew/bin/brew shellenv)
    fi
  fi
fi

if [ -s "$HOME/.Brewfile" ]; then
  echo '📦 Checking if we need to install packages…'
  if ! brew bundle check --global > /dev/null 2>&1; then
    # shellcheck disable=SC2016
    echo '📦 Install missing packages…'
    brew bundle install --global
  fi
fi

# Link all linkable files
while IFS= read -r -d '' src; do
  dst="$HOME/.$(basename "${src%.*}")"
  if [ ! -L "$dst" ]; then
    echo "🔗 Linking $src → $dst"
    ln -Ff -s "$src" "$dst"
  fi
done <  <(find -H "$DIR" -maxdepth 2 -name '*.symlink' -not -path '*.git*' -print0)

# Run all install.sh scripts
find "$DIR" -maxdepth 2 -name install.sh -exec echo "👟 Running {}…" \; -exec {} \;

printf "\\n\\033[01;32m%s\033[0m\\n\\n" '🏁 All done!!'
