---
last_check:
  etag: '"21634c26520aea84cb5473dee6746f6e"'
  version: 1.8.8
  at: 1522237004
checked_completion: true
completion_version: 1.8.8
endpoints:
  https://api.travis-ci.org/:
repos:
  lildude/build-gh-pages-from-travis:
    endpoint: https://api.travis-ci.org/
  lildude/micropub-github-pages:
    endpoint: https://api.travis-ci.org/
