---
last_check:
  etag: '"f5f7caaf148df6408d8b04661b7edd51"'
  version: 1.8.9
  at: 1544456670
checked_completion: true
completion_version: 1.8.9
endpoints:
  https://api.travis-ci.org/: {}
repos:
  lildude/build-gh-pages-from-travis:
    endpoint: https://api.travis-ci.org/
  lildude/micropub-github-pages:
    endpoint: https://api.travis-ci.org/
  lildude/gonefora.run:
    endpoint: https://api.travis-ci.org/
  atom/atom:
    endpoint: https://api.travis-ci.org/
