name: Initial Bootstrap

on: [push]

jobs:
  run:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap
      run: script/bootstrap
  shellcheck:
    name: Shellcheck
    runs-on: ${{ matrix.os }}
    steps:
      - run: script/shellcheck.sh