name: Initial Bootstrap

on: [push, pull_request]

jobs:
  run:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Copy to $HOME
      run: cp -Rf $GITHUB_WORKSPACE $HOME/.dotfiles
      shell: bash
    - name: Bootstrap
      run: |
        cd $HOME/.dotfiles
        script/bootstrap